pipeline {
    agent {
        label 'ubuntu18'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        post {
		always {
			junit 'target/surefire-reports/*.xml'
			cucumber fileIncludePattern: "target/surefire-reports/cucumber.json"
			emailext body: '''${SCRIPT, template="JenkinsQaReportEmail.template"}''', recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']], subject: 'Test', to: 'george.caluta@ibapplications.com' , mimeType: 'text/html'
		}
	}
}
